[[constraint]]
  name = "github.com/alicebob/miniredis"
  version = "2.4.5"

[[constraint]]
  name = "github.com/allegro/bigcache"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/mna/redisc"
  version = "1.1.3"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_model"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
